#!/usr/bin/bash

readonly PORT=80

display_ip_info(){
    echo "IP informations about wlp3s0"
    local regex='inet\s[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}.[0-9]{1,3}'
    local ipData=$(ifconfig wlp3s0 | egrep -o $regex)
    local i=0
    echo "   $ipData"
}

start_python_http_server(){
    echo "Starting HTTP Server on $(pwd) using port $PORT"
    sudo /usr/bin/python2 -m SimpleHTTPServer $PORT
}

main(){
    echo "HTTP server on current directory"
    echo -e "================================\n"
    display_ip_info
    echo "--------------------------------"
    start_python_http_server
}

main
